language: node_js
node_js:
  - "6"
  - "6.1"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm run test
after_success:
  - npm run coveralls